# Generated by Django 6.0.7 on 2026-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_restrictions',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
