# Generated by Django 6.0.7 on 2026-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account id (acct_...). Blank until onboarding starts.', max_length=64),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='True once Stripe confirms this account can receive transfers.'),
        ),
    ]
