# Generated by Django 6.0.7 on 2026-09-24 09:44

from django.db import migrations, models


def backfill_checked_in_count(apps, schema_editor):
    # Before group check-in, one scan marked the whole booking ATTENDED —
    # treat those as fully admitted so they can't be scanned in again.
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(status="attended").update(checked_in_count=models.F("quantity"))


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_one_active_booking_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_checked_in_count, migrations.RunPython.noop),
    ]
